### ISSUE TITLE
Add example of using contexts with parameters

### ISSUE THREAD

**Issue by owenbrown** [dialogflow/dialogflow-python-client-v2#28]
My team is having difficulty using the SDK with contexts that have parameters. 

The documentation is messed up. 
On 
    http://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2beta1/types.html?
    highlight=QueryParameters#dialogflow_v2beta1.types.Context
    
    section: dialogflow_v2beta1.types.Context

It says to go to "https://dialogflow.com/docs/actions-and-parameters" to get the format for parameters. The URL it links to does nothing to explain the format.

Simply passing the key/value pairs as  in the context doesn't work. It generates the error: 

`KeyError: 'foo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/venv/chalicelib/df_driver/__init__.py", line 727, in <module>
    "parameters": inner_parameters
  File "/Users/user/venv/lib/python3.6/site-packages/dialogflow_v2beta1/gapic/sessions_client.py", line 204, in detect_intent
    input_audio=input_audio)
  File "/Users/user/venv/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 516, in init
    new_val = field.message_type._concrete_class(**field_value)
  File "/Users/user/venv/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 503, in init
    copy.add(**val)
  File "/Users/user/venv/lib/python3.6/site-packages/google/protobuf/internal/containers.py", line 372, in add
    new_element = self._message_descriptor._concrete_class(**kwargs)
  File "/Users/user/venv/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 516, in init
    new_val = field.message_type._concrete_class(**field_value)
  File "/Users/user/venv/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 484, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "/Users/user/venv/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 548, in _GetFieldByName
    (message_descriptor.name, field_name))
ValueError: Protocol message Struct has no "foo" field.`

The detect_intent docs say:

...
query_params (Union[dict, ~dialogflow_v2beta1.types.QueryParameters]): Optional. The parameters of this query.
                If a dict is provided, it must be of the same form as the protobuf
                message :class:`~dialogflow_v2beta1.types.QueryParameters`
...

This format isn't documented anywhere. So unless the user has a really deep understanding of protocol buffers, users can't pass parameters in contexts while calling detect_intent.d

The sample code should really include a call to detect_intent that passes in a context with parameters. 

In the absence of adding this to the sample code, could you at least respond to this request with an example of how to call detect_intent with a context that has parameters {"foo": ["bar", "baz"]}?

**Comment by mikozh** [comment]
Have the same problem :( Can not figure out how to pass parameters

**Comment by atimzhao** [comment]
Having the same issue! Please help

**Comment by Starbutter-jpicar** [comment]
Having this issue as well, very unclear how to use parameters here. Anyone have any ideas?

**Comment by Starbutter-jpicar** [comment]
Also having this problem; it's very unclear how parameters are supposed to be formatted.

**Comment by lordrubenbp** [comment]
same problem here!, any know where i can found context id??

**Comment by owenbrown** [comment]
import dialogflow
import os

GOOGLE_AUTHENTICATION_FILE_NAME = "file.json"
current_directory = os.path.dirname(os.path.realpath(__file__))
path = os.path.join(current_directory, GOOGLE_AUTHENTICATION_FILE_NAME)
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = path

GOOGLE_PROJECT_ID = "exampleproject"
session_id = "abc-123"
context_short_name = "does_not_matter"

context_name = "projects/" + GOOGLE_PROJECT_ID + "/agent/sessions/" + session_id + "/contexts/" + \
               context_short_name.lower()


parameters = dialogflow.types.struct_pb2.Struct()
parameters["foo"] = "bar"

context_1 = dialogflow.types.context_pb2.Context(
    name=context_name,
    lifespan_count=2,
    parameters=parameters
)

query_params_1 = {"contexts": [context_1]}

language_code = 'en'


def detect_intent_with_parameters(project_id, session_id, query_params, language_code):
    """Returns the result of detect intent with texts as inputs.

    Using the same `session_id` between requests allows continuation
    of the conversaion."""
    session_client = dialogflow.SessionsClient()

    session = session_client.session_path(project_id, session_id)
    print('Session path: {}\n'.format(session))

    text = "this is as test"

    text_input = dialogflow.types.TextInput(
        text=text, language_code=language_code)

    query_input = dialogflow.types.QueryInput(text=text_input)

    response = session_client.detect_intent(
        session=session, query_input=query_input,
        query_params=query_params
    )

    print('=' * 20)
    print('Query text: {}'.format(response.query_result.query_text))
    print('Detected intent: {} (confidence: {})\n'.format(
        response.query_result.intent.display_name,
        response.query_result.intent_detection_confidence))
    print('Fulfillment text: {}\n'.format(
        response.query_result.fulfillment_text))


detect_intent_with_parameters(
    project_id=GOOGLE_PROJECT_ID,
    session_id=session_id,
    query_params=query_params_1,
    language_code=language_code
)

**Comment by saiffero** [comment]
how do i get this context data which is passed as output context can any one help ? (In python only)
