### ISSUE TITLE
Problems on trying to explicitly use credentials by specifying the private key file on SessionsClient.

### ISSUE THREAD

**Issue by mukkah** [dialogflow/dialogflow-python-client-v2#37]
Hi,

I`m using the SDK  dialogflow V2 beta1 for python 2.7 on a CentOS 7 server and when I try to explicitly pass the private key file for creating a session like this:
session_client = dialogflow.SessionsClient(credentials='credentials path')

I get the following error (final line. I can add the whole stack if needed):
"Getting metadata from plugin failed with error: 'str' object has no attribute 'before_request'"

If no credentials is passed, setting the GOOGLE_APPLICATION_CREDENTIALS env variable works, but it does not fit for me, since I'd like to use many agents (project-id) on the same server.

Is it a known issue, or should I make it in a different way?

I`d appreciate any help.

Thanks!

**Comment by renboyan** [comment]
The type of 'credentials' is google.auth.credentials.Credentials.
So, you can make it work by following:

from google.oauth2 import service_account
credentials = service_account.Credentials.from_service_account_file('credentials.json')
session_client = dialogflow.SessionsClient(credentials=credentials)

**Comment by mukkah** [comment]
It worked! Thanks a lot!

**Comment by I2304** [comment]
Is the path the relative path? I am getting  a "No such file or directory" error.
