### ISSUE TITLE
Permission Denied: 403 Dialogflow API has not been used in project before or it is disabled.

### ISSUE THREAD

**Issue by Hesmond** [dialogflow/dialogflow-python-client-v2#47]
**Issue:**
Getting permission error when testing using "detect_intent_texts.py" from samples
> google.api_core.exceptions.PermissionDenied: 403 Dialogflow API has not been used in project 563584335869 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dialogflow.googleapis.com/overview?project=563584335869 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

I followed the instructions from "https://dialogflow.com/docs/reference/v2-auth-setup" to set up authentication & was able to trigger the final http post request successfully.

My project Id is not "563584335869", so when I visit that link it shows that I don't have access. Do I need to do some extra setting to point it to my project or something?

_Sorry if I missed out some information, do let me know what else is needed, thanks!_

**Comment by lukaszbk** [comment]
@Hesmond, did you follow these instructions carefully: https://github.com/dialogflow/dialogflow-python-client-v2/blob/master/samples/README.rst#before-you-begin? In particular, are you passing --project-id flag when calling detect_intent_texts.py?

**Comment by Hesmond** [comment]
@lukaszbk, yup I followed the instructions there, only thing is I didn't use the sample agent, I created my own called "Small-Talk".

As for the command trigger, I used the following command to trigger:
`python detect_intent_texts.py --project-id small-talk-b4c3b --session-id session-play-1 "hi"`

also tried,
`python detect_intent_texts.py --project-id "small-talk-b4c3b" --session-id "session-play-1" "hi"`

I got my project id from 
> Dialog flow console > agent > settings > General > Google Project > Project ID

**Comment by Hesmond** [comment]
**Quick Update:**
I created another agent in DialogFlow, did the entire process again and triggered the file, still hitting the same issue.

`python detect_intent_texts.py --project-id small-talk-v2 --session-id session-play-1 "hi"`

Weirdest part is, even after changing the project id, it is still giving me the following error:

> google.api_core.exceptions.PermissionDenied: 403 Dialogflow API has not been used in project 563584335869 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dialogflow.googleapis.com/overview?project=563584335869 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

So, I guess it's got to do with my comp that's caching the project id or something?
