### ISSUE TITLE
TypeError on detect_intent with query_input specified as dict

### ISSUE THREAD

**Issue by gmolau** [dialogflow/dialogflow-python-client-v2#53]
According to the documentation [`SessionsClient.detect_intent`](http://dialogflow-python-client-v2.readthedocs.io/en/latest/gapic/v2beta1/api.html#dialogflow_v2beta1.SessionsClient.detect_intent) should work with a dict as the query_input. The docs don't say what keys must be in that dict, but assuming they are the same as in the `dialogflow_v2beta1.types.QueryInput` classes I tried this example (which is taken almost word for word from the documentation):

```
$ ipython
Python 3.6.4 (default, Jan  6 2018, 11:51:59) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from dialogflow_v2beta1 import SessionsClient

In [2]: client = SessionsClient()

In [3]: session = client.session_path('MY_AGENT', 'abcdefg123')

In [4]: query_input = {'text': 'talk to MY_AGENT', 'language_code': 'en-US'}

In [5]: response = client.detect_intent(session, query_input)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-b6d5f075ffb7> in <module>()
----> 1 response = client.detect_intent(session, query_input)

~/<project_dir>/venv/lib/python3.6/site-packages/dialogflow_v2beta1/gapic/sessions_client.py in detect_intent(self, session, query_input, query_params, input_audio, retry, timeout)
    202             query_input=query_input,
    203             query_params=query_params,
--> 204             input_audio=input_audio)
    205         return self._detect_intent(request, retry=retry, timeout=timeout)
    206 

TypeError: Parameter to MergeFrom() must be instance of same class: expected google.cloud.dialogflow.v2beta1.TextInput got str.
```

Wrapping the input in a `dialogflow.v2beta1.types.QueryInput` works, but that requires two additional object instantiations and should not be necessary according to the current documentation.

**Comment by madongfly** [comment]
As the documentation says "If a dict is provided, it must be of the same form as the protobuf message QueryInput", so you need something like {'text': {'text': 'talk to MY_AGENT', 'language_code': 'en-US'}}

**Comment by gmolau** [comment]
Ah ok, makes sense:)
