### ISSUE TITLE
Intent training phrases returning empty list 

### ISSUE THREAD

**Issue by charlielu05** [dialogflow/dialogflow-python-client-v2#60]
Having issues when I'm trying to print out the training phrases for the individual intents of the agent:

```
intents_client = dialogflow.IntentsClient()

parent = intents_client.project_agent_path(project_id)

intents = intents_client.list_intents(parent)

for intent in intents:
    print('=' * 40)
    print('Intent name: {}'.format(intent.name))
    print('Intent display_name: {}'.format(intent.display_name))
    print('Intent training phrases: {}'.format(intent.training_phrases))
    print('Intent messages: {}'.format(intent.messages))
```
The intent name, display name and message are all displayed apart from training phrases which always seems to be an empty list :(

**Comment by AlexSissoko** [comment]
You have to set the intent_view argument of list_intents to INTENT_VIEW_FULL.
So, 
`intents = intents_client.list_intents(parent, intent_view='INTENT_VIEW_FULL'`

**Comment by charlielu05** [comment]
@AlexSissoko Thank you so much for the reply! Will try it out!

**Comment by AlexSissoko** [comment]
Glad I could help. Also, if you ever have problems with understanding some of the methods, check out https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2. Its helped me out quite a bit.
