### ISSUE TITLE
Create entity of agent

### ISSUE THREAD

**Issue by Akashutreja** [dialogflow/dialogflow-python-client-v2#65]
Hi,
Can anyone please tell me how to create entity in an agent? I am able to create entity_type using following.

```

def create_entity_type(project_id, display_name, kind):
    """Create an entity type with the given display name."""
    print("kind:")
    print(kind)
    project_id="fir-chatbot-ccc2d"
    entity_types_client = dialogflow.EntityTypesClient()
    parent = entity_types_client.project_agent_path(project_id)
    entity_type = dialogflow.types.EntityType(
        display_name=display_name, kind=kind)
    response = entity_types_client.create_entity_type(parent, entity_type)
    print('Entity type created: \n{}'.format(response))

``` 
But above code doesn't generate name field which should be automatically as given here.
https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2#google.cloud.dialogflow.v2.EntityType

Therefore entity_type which i created doesn't have any entity_type_id and when i run **_get_entity_type_ids** defined here.
https://github.com/dialogflow/dialogflow-python-client-v2/blob/master/samples/entity_type_management.py
I got entity_type_id as [].
so to create an entity I need entity_type_id as defined here.
https://github.com/dialogflow/dialogflow-python-client-v2/blob/master/samples/entity_management.py
But entity_type_id is empty.
please help
Thanks

**Comment by dysnomia** [comment]
The `response` returned by `create_entity_type` should return the auto-generated named populated by create. Could you please take a look at whether it is populated?

**Comment by Akashutreja** [comment]
yes, it works actually I haven't given it IAM permissions.
Thanks
