### ISSUE TITLE
maximum number of intents

### ISSUE THREAD

**Issue by Mahendra-Chouhan** [dialogflow/dialogflow-python-client-v2#75]
https://github.com/dialogflow/dialogflow-python-client-v2/blob/30ae437d47c42b60cc08e05db243c02d5327fbee/dialogflow_v2/gapic/agents_client.py#L539

What is the _maximum number_ of intents support from this code?

**Comment by jrash06** [comment]
There is a limit on the size of zip package uploaded, which is 128MB.

**Comment by Mahendra-Chouhan** [comment]
thanks
